// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FlyCat_ActorMaxLevel","status":false,"description":"属性破限、角色等级限制、角色等级名称自定义","parameters":{"等级上限":"99","人物HP上限":"9999","人物MP上限":"9999","人物其他属性上限":"9999","敌人HP上限":"999999","敌人MP上限":"9999","敌人其他属性上限":"9999"}}
];
